name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Generate java soures
      run: lein javac
    - name: Run tests
      run: lein test
    - name: Generate pom
      run: lein pom
    - name: Deploy to Github Package Registry
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      run: mvn --settings .github/workflows/settings.xml deploy
